In [1]:
import pandas as pd
import numpy as np

# -------------------------------
# 1. NumPy Basics
# -------------------------------
print("NumPy Basics")
array = np.array([1, 2, 3, 4, 5])
print("Array:", array)
print("Mean:", np.mean(array))
print("Standard Deviation:", np.std(array))
print("Max:", np.max(array))
print("Min:", np.min(array))
print("Sum:", np.sum(array))
print()

# -------------------------------
# 2. Create DataFrame with Pandas
# -------------------------------
print("Pandas DataFrame")
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 29],
    'Salary': [50000, 60000, 70000, 80000, 62000],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR']
}
df = pd.DataFrame(data)
print(df)
print()

# -------------------------------
# 3. Basic Statistics with Pandas
# -------------------------------
print("Basic Statistics")
print("Describe:\n", df.describe())
print("Mean Age:", df['Age'].mean())
print("Median Salary:", df['Salary'].median())
print("Mode Department:", df['Department'].mode()[0])
print("Age Standard Deviation:", df['Age'].std())
print("Salary Correlation with Age:\n", df[['Age', 'Salary']].corr())
print()

# -------------------------------
# 4. Grouping & Aggregation
# -------------------------------
print("Group by Department")
grouped = df.groupby('Department').agg({
    'Salary': ['mean', 'max', 'min'],
    'Age': 'mean'
})
print(grouped)
print()

# -------------------------------
# 5. Filtering and Sorting
# -------------------------------
print("People with salary > 60000")
print(df[df['Salary'] > 60000])
print()

print("Sorted by Age descending")
print(df.sort_values(by='Age', ascending=False))


NumPy Basics
Array: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Max: 5
Min: 1
Sum: 15

Pandas DataFrame
      Name  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000         IT
2  Charlie   35   70000         IT
3    David   40   80000    Finance
4      Eva   29   62000         HR

Basic Statistics
Describe:
             Age        Salary
count   5.00000      5.000000
mean   31.80000  64400.000000
std     5.80517  11260.550608
min    25.00000  50000.000000
25%    29.00000  60000.000000
50%    30.00000  62000.000000
75%    35.00000  70000.000000
max    40.00000  80000.000000
Mean Age: 31.8
Median Salary: 62000.0
Mode Department: HR
Age Standard Deviation: 5.805170109479997
Salary Correlation with Age:
             Age   Salary
Age     1.00000  0.98823
Salary  0.98823  1.00000

Group by Department
             Salary                 Age
               mean    max    min  mean
Department                             
Finance     80000.0  800

In [2]:
import numpy as np

# Create 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

# Transpose
print("Transpose:\n", matrix.T)

# Element-wise operations
print("Matrix + 10:\n", matrix + 10)
print("Matrix squared:\n", matrix ** 2)

# Create random arrays
rand_array = np.random.rand(5)  # Uniform [0, 1)
print("Random array:", rand_array)

normal_array = np.random.randn(5)  # Normal distribution
print("Normally distributed:", normal_array)

# Reshape
reshaped = np.arange(12).reshape((3, 4))
print("Reshaped (3x4):\n", reshaped)


Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Matrix + 10:
 [[11 12 13]
 [14 15 16]]
Matrix squared:
 [[ 1  4  9]
 [16 25 36]]
Random array: [0.49542949 0.34068267 0.9923322  0.44733521 0.16839622]
Normally distributed: [ 1.2593404  -1.66196638 -0.76048577  0.33230456  0.29855504]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
